#!/bin/bash
# fork-overlay.sh — overlay the fixed UE4SS fork stack into the game root,
# then hand off to the stock obnyis servermanager.
#
# Why: the obnyis image's setup_ue4ss() downloads the fragile Yangff UE4SS build
# (SHA-pinned) when ./PalServerUE4SS.sh is missing from the game root. The game
# root is a volume, so image-baked files at /palworld would be shadowed. Instead
# we bake the payload at /opt/ue4ss-fork and copy it in on every boot. The
# servermanager's existence check then short-circuits: it never downloads Yangff,
# and starts the game with our LD_PRELOAD launcher.
#
# Runs as the steam user (entrypoint gosu's us after PUID/PGID setup).

set -e

source /includes/colors.sh

FORK_ROOT=/opt/ue4ss-fork
GAME_ROOT=/palworld
UE4SS_DEST="${GAME_ROOT}/Pal/Binaries/Linux/ue4ss"

if [ ! -d "${FORK_ROOT}" ]; then
    ew "> fork-overlay: /opt/ue4ss-fork missing, continuing with stock behavior"
    exec /scripts/servermanager.sh "$@"
fi

ei ">>> fork-overlay: installing fixed UE4SS stack"
mkdir -p "${UE4SS_DEST}" "${UE4SS_DEST}/UE4SS_Signatures" "${UE4SS_DEST}/Mods"

# Core payload — overwrite unconditionally so updates to the image always ship
cp -f "${FORK_ROOT}/libUE4SS.so" "${UE4SS_DEST}/libUE4SS.so"
[ -f "${FORK_ROOT}/MemberVariableLayout.ini" ] && cp -f "${FORK_ROOT}/MemberVariableLayout.ini" "${UE4SS_DEST}/MemberVariableLayout.ini"
[ -f "${FORK_ROOT}/UE4SS-settings.ini" ] && cp -f "${FORK_ROOT}/UE4SS-settings.ini" "${UE4SS_DEST}/UE4SS-settings.ini"
[ -f "${FORK_ROOT}/mods.txt" ] && cp -f "${FORK_ROOT}/mods.txt" "${UE4SS_DEST}/mods.txt"

# Signatures (leak-fix activation)
[ -f "${FORK_ROOT}/UE4SS_Signatures/FName_ToString.lua" ] && cp -f "${FORK_ROOT}/UE4SS_Signatures/FName_ToString.lua" "${UE4SS_DEST}/UE4SS_Signatures/FName_ToString.lua"

# Mods are (re)installed by fork-postinstall.sh via the custom-script hook AFTER
# fresh_install/update (steamcmd wipes Mods/ on install) — nothing to do here.

# The LD_PRELOAD launcher — the servermanager checks ./PalServerUE4SS.sh to decide
# whether UE4SS is installed. We ship the launcher ourselves so the existence
# check passes and Yangff is never downloaded.
if [ ! -f "${GAME_ROOT}/PalServerUE4SS.sh" ]; then
    ei ">>> fork-overlay: creating PalServerUE4SS.sh launcher"
    cat > "${GAME_ROOT}/PalServerUE4SS.sh" <<'EOF'
#!/bin/bash
# Generated by fork-overlay.sh — runs the game with the fixed fork's libUE4SS.so
# via LD_PRELOAD (same mechanism the obnyis image uses for stock UE4SS).
UE_PROJECT_ROOT=/palworld
export LD_PRELOAD="${UE_PROJECT_ROOT}/Pal/Binaries/Linux/ue4ss/libUE4SS.so"
"${UE_PROJECT_ROOT}/Pal/Binaries/Linux/PalServer-Linux-Shipping" Pal "$@"
EOF
    chmod +x "${GAME_ROOT}/PalServerUE4SS.sh"
    chown steam:steam "${GAME_ROOT}/PalServerUE4SS.sh" 2>/dev/null || true
fi

es ">>> fork-overlay: fixed UE4SS stack in place"

exec /scripts/servermanager.sh "$@"
