-- UE4SSStatus: Shows UE4SS is active
-- This mod is auto-generated by UE4SS

print('[UE4SS] UE4SSStatus mod loaded - UE4SS is active and running!')

-- Note: On Linux limited mode, UE hooks (BeginPlay, InitGameState) are not available.
-- This mod simply confirms that the Lua mod loader is working.
